/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package book.rental.system;


import java.sql.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Shaily Gupta
 */
public class adminsignup extends javax.swing.JFrame {
    
    /**
     * Creates new form adminsignup
     */
    public adminsignup() {
        initComponents();
            
    }
    
    public boolean validationAsignup(){
      String name = txtusername.getText();
      String email = txtemail.getText();
      String phoneno = txtphone.getText();
      String pass = txtpass.getText(); 
      String conpass = txtcpwd.getText(); 
        if(name.equals("" )){
            JOptionPane.showMessageDialog(this,"Username Required!","Warning",2);
            return false;
        }
        
         if(email.equals("")){
            JOptionPane.showMessageDialog(this,"Please Enter your Email!","Warning",2);
            return false;
        }
         
         if(!email.matches("^.+@.+\\..+$")){
            JOptionPane.showMessageDialog(this,"Please Enter Valid Email!","Warning",2);
            return false;
        }
         
          if(phoneno.equals("")){
            JOptionPane.showMessageDialog(this,"Please Enter Your Phone no.","Warning" ,2);
            return false;
        }
          
          if(phoneno.length()>10){
            JOptionPane.showMessageDialog(this,"Phone no. is to long","Warning" ,2);
            return false;
        }
          
          if(phoneno.length()<10){
            JOptionPane.showMessageDialog(this,"Phone no. is to short","Warning" ,2);
            return false;
        }
          
           if(pass.equals("")){
            JOptionPane.showMessageDialog(this,"Enter password!","Warning",2);
            return false;
        }
           
            if(conpass.equals("")){
            JOptionPane.showMessageDialog(this,"enter confirm password!","Warning",2);
            return false;
        }
             if(!pass.equals(conpass)){
            JOptionPane.showMessageDialog(this,"re_enter password!","Warning",2);
            return false;
        }
        
            return true;
      }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        txtcpwd = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        btnsignpu = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        chkboxreme = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("BTB");
        jLabel12.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jLabel12MouseWheelMoved(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 40));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setText("Create an account");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 300, 50));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("USERNAME");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 90, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("  EMAIL ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 90, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("PHONE NO. ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 90, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("PASSWORD");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("CONFIRM PASSWORD");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, 20));

        txtusername.setBackground(new java.awt.Color(242, 242, 222));
        txtusername.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(51, 0, 51));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusernameKeyTyped(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 290, 30));

        txtemail.setBackground(new java.awt.Color(242, 242, 222));
        txtemail.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtemail.setForeground(new java.awt.Color(51, 0, 51));
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 290, 30));

        txtphone.setBackground(new java.awt.Color(242, 242, 222));
        txtphone.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtphone.setForeground(new java.awt.Color(51, 0, 51));
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });
        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphoneKeyTyped(evt);
            }
        });
        getContentPane().add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 290, 30));

        txtpass.setBackground(new java.awt.Color(242, 242, 222));
        txtpass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtpass.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 240, 30));

        txtcpwd.setBackground(new java.awt.Color(242, 242, 222));
        txtcpwd.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtcpwd.setForeground(new java.awt.Color(51, 0, 51));
        txtcpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpwdActionPerformed(evt);
            }
        });
        getContentPane().add(txtcpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 240, 30));

        btnlogin.setBackground(new java.awt.Color(102, 51, 0));
        btnlogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 204));
        btnlogin.setText("Login");
        btnlogin.setBorder(null);
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 70, 30));

        btnsignpu.setBackground(new java.awt.Color(0, 102, 102));
        btnsignpu.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnsignpu.setForeground(new java.awt.Color(234, 234, 193));
        btnsignpu.setText("SIGN UP");
        btnsignpu.setBorder(null);
        btnsignpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignpuActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 170, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Already have an account?");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 180, 30));

        jLabel14.setBackground(new java.awt.Color(102, 51, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 51, 0));
        jLabel14.setText("X");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 30, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 350, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 70, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book (2).png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        chkboxreme.setBackground(new java.awt.Color(241, 231, 231));
        chkboxreme.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkboxreme.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        chkboxreme.setOpaque(true);
        chkboxreme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxremeActionPerformed(evt);
            }
        });
        getContentPane().add(chkboxreme, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 30, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Letters_1.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jLabel12MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseWheelMoved

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here
        adminLogin obj1 = new adminLogin();
        obj1.show();
        dispose();

    }//GEN-LAST:event_btnloginActionPerformed

    private void btnsignpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignpuActionPerformed
        // TODO add your handling code here:
        
                
                    if(validationAsignup()==true){

               String query;
           try{    
                String name = txtusername.getText();
                String email = txtemail.getText();
                String phoneno = txtphone.getText();
                String pass = txtpass.getText(); 
                String conpass = txtcpwd.getText(); 

               Class.forName("com.mysql.cj.jdbc.Driver");
               Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_rental_system" , "root" , "123456");
               Statement st = con.createStatement();
               query = "INSERT INTO adminsignup(username,email,phone,password)"+"VALUES('"+name+"' , '"+email+"' , '"+phoneno+"' ,'"+pass+"'  )";
               st.execute(query);

                    txtusername.setText("");
                    txtemail.setText("");
                    txtphone.setText("");
                    txtpass.setText("");
                    txtcpwd.setText("");

                    JOptionPane.showMessageDialog(this, "Your account has been created successfully!!");

                   adminLogin obj1 = new adminLogin();
                   obj1.show();
                   dispose(); 


           }catch(Exception e){
               System.out.println("Error!" + e.getMessage());
           }
        }
        
        
        

    }//GEN-LAST:event_btnsignpuActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtcpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpwdActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here
        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void txtusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyTyped
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtusernameKeyTyped

    private void txtphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtphoneKeyTyped

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        welcome obj = new welcome();
        obj.show();
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void chkboxremeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxremeActionPerformed
        // TODO add your handling code here:
        if(chkboxreme.isSelected()){
            txtpass.setEchoChar((char)0);
            txtcpwd.setEchoChar((char)0);
        }
        else{
            txtpass.setEchoChar('*');
            txtcpwd.setEchoChar('*');
        }
    }//GEN-LAST:event_chkboxremeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminsignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnsignpu;
    private javax.swing.JCheckBox chkboxreme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txtcpwd;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
