/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package book.rental.system;

import static book.rental.system.User_fp.txtphone;
import javax.swing.JOptionPane;

/**
 *
 * @author Shaily Gupta
 */
public class card_pay extends javax.swing.JFrame {

    /**
     * Creates new form card
     */
    public card_pay() {
        initComponents();
    }
    
     public boolean validationcard(){
      String num = txtno.getText();
     
      String cvv = txtcvv.getText(); 
      String valid = txtvalid.getText(); 
        
         if(num.equals("")){
            JOptionPane.showMessageDialog(this,"enter your card no.","Warning",2);
            return false;
        }
          if(num.length()>12){
            JOptionPane.showMessageDialog(this," card nois too long","Warning" ,2);
            return false;
        }
          
          if(num.length()<12){
            JOptionPane.showMessageDialog(this,"card no. is to short","Warning" ,2);
            return false;
        }
         
          if(cvv.equals("")){
            JOptionPane.showMessageDialog(this,"enter your cvv.","Warning",2);
            return false;
        }
          
           if(cvv.length()<3){
            JOptionPane.showMessageDialog(this," cvv is too short","Warning" ,2);
            return false;
        }
           
            if(cvv.length()>3){
            JOptionPane.showMessageDialog(this," cvv is too long","Warning" ,2);
            return false;
        }
          
           if(valid.equals("")){
            JOptionPane.showMessageDialog(this,"enter your vilidity.","Warning",2);
            return false;
        }
         return true;
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtvalid = new javax.swing.JTextField();
        txtcvv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btbproceed = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(166, 190, 166));
        jPanel2.setPreferredSize(new java.awt.Dimension(576, 406));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(582, 453));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("CARD PAYMENT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 222, 40));

        txtno.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        txtno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnoKeyPressed(evt);
            }
        });
        getContentPane().add(txtno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 245, 35));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Card Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 40));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("Valid Till");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 86, 40));

        txtvalid.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        getContentPane().add(txtvalid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 180, 30));

        txtcvv.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        getContentPane().add(txtcvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 180, 30));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("CVV");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        btbproceed.setBackground(new java.awt.Color(0, 51, 255));
        btbproceed.setFont(new java.awt.Font("Swis721 Ex BT", 1, 18)); // NOI18N
        btbproceed.setForeground(new java.awt.Color(204, 255, 255));
        btbproceed.setText("Pay");
        btbproceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbproceedActionPerformed(evt);
            }
        });
        getContentPane().add(btbproceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 120, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 30, 60));

        jLabel7.setBackground(new java.awt.Color(166, 190, 166));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btbproceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbproceedActionPerformed
        // TODO add your handling code here:
        if(validationcard()==true){
        JOptionPane.showMessageDialog(null, "payment successfull");
        
        }

    }//GEN-LAST:event_btbproceedActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        payment ob = new payment();
        ob.show();
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void txtnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnoKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtnoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(card_pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(card_pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(card_pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(card_pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new card_pay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbproceed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtcvv;
    private javax.swing.JTextField txtno;
    private javax.swing.JTextField txtvalid;
    // End of variables declaration//GEN-END:variables
}
