/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package book.rental.system;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.Blob;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shaily Gupta
 */
public class edit_books extends javax.swing.JFrame {

    /**
     * Creates new form edit_books
     */
    public edit_books() {
        initComponents();
        table_update();
    }
         
    Connection con;
    PreparedStatement insert;
    ResultSet rs = null;
    String path2 = null;
   
     private void table_update(){
           int c;
           try {
           Class.forName("com.mysql.cj.jdbc.Driver");
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_rental_system" , "root" , "123456");
            insert = con.prepareStatement("SELECT * FROM admin_book");
            ResultSet rs = insert.executeQuery();
            ResultSetMetaData rss = rs.getMetaData();
            c = rss.getColumnCount();
            
            DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
            df.setRowCount((0));
            
            while(rs.next()){
                Vector v2 = new Vector();
                for(int a=1;a<=c;a++){
                   v2.add(rs.getString("sr"));
                   v2.add(rs.getString("name"));
                   v2.add(rs.getString("genres"));
                   v2.add(rs.getString("author"));
                   v2.add(rs.getString("rent_amt"));
                   v2.add(rs.getBytes("image"));
                   Blob image = rs.getBlob(5);
                   byte[] bytea = image.getBytes(1, (int)image.length());
                   
                        
                        ImageIcon icon = new ImageIcon(bytea);
                        lbl_photo.setIcon(icon);

//                    try {
//                        FileOutputStream fos=new FileOutputStream(path2);
//                        fos.write(bytea);
//                        ImageIcon icon = new ImageIcon(bytea);
//                        lbl_photo.setIcon(icon);
//                    } catch (FileNotFoundException ex) {
//                        Logger.getLogger(edit_books.class.getName()).log(Level.SEVERE, null, ex);
//                    } catch (IOException ex) {
//                        Logger.getLogger(edit_books.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                   
             }
                
                df.addRow(v2);
            }
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(add_books.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         catch (SQLException ex) {
            Logger.getLogger(add_books.class.getName()).log(Level.SEVERE, null, ex);
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btndel = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtgenres = new javax.swing.JTextField();
        txtauthor = new javax.swing.JTextField();
        txtsr = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        btnaddbook = new javax.swing.JButton();
        txtcover = new javax.swing.JLabel();
        txtrent = new javax.swing.JTextField();
        lbl_photo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("   !!   EDIT BOOKS  !!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 440, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book (2).png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("BTB");
        jLabel12.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jLabel12MouseWheelMoved(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("AUTHOR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Sr no.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 60, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 110, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("GENRES");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, 30));

        btndel.setBackground(new java.awt.Color(102, 102, 0));
        btndel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btndel.setForeground(new java.awt.Color(255, 255, 255));
        btndel.setText("DELETE");
        btndel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 0), null, null, new java.awt.Color(0, 102, 51)));
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });
        getContentPane().add(btndel, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 510, 210, 40));

        btnedit.setBackground(new java.awt.Color(102, 102, 0));
        btnedit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("UPDATE");
        btnedit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 0), null, null, new java.awt.Color(0, 102, 51)));
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 210, 40));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText(" RENT AMOUNT");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, 30));

        txtname.setBackground(new java.awt.Color(215, 248, 248));
        txtname.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(0, 0, 51));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 210, 30));

        txtgenres.setBackground(new java.awt.Color(215, 248, 248));
        txtgenres.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtgenres.setForeground(new java.awt.Color(0, 0, 51));
        txtgenres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenresActionPerformed(evt);
            }
        });
        getContentPane().add(txtgenres, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 210, 30));

        txtauthor.setBackground(new java.awt.Color(215, 248, 248));
        txtauthor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtauthor.setForeground(new java.awt.Color(0, 0, 51));
        txtauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtauthorActionPerformed(evt);
            }
        });
        getContentPane().add(txtauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 210, 30));

        txtsr.setBackground(new java.awt.Color(215, 248, 248));
        txtsr.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtsr.setForeground(new java.awt.Color(0, 0, 51));
        txtsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsrActionPerformed(evt);
            }
        });
        getContentPane().add(txtsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 210, 30));

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "sr no.", "NAME", "GENRES", "AUTHOR", "RENT AMT", "IMAGE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(245, 223, 223));
        jTable1.setSelectionForeground(new java.awt.Color(0, 51, 51));
        jTable1.setShowGrid(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 730, 370));

        jLabel14.setBackground(new java.awt.Color(102, 51, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 51, 0));
        jLabel14.setText("X");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, 30, 40));

        btnaddbook.setBackground(new java.awt.Color(102, 102, 0));
        btnaddbook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnaddbook.setForeground(new java.awt.Color(255, 255, 255));
        btnaddbook.setText("ADD  BOOKS");
        btnaddbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddbookMouseClicked(evt);
            }
        });
        getContentPane().add(btnaddbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 210, 40));

        txtcover.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtcover.setText("Cover Page");
        getContentPane().add(txtcover, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, 30));

        txtrent.setBackground(new java.awt.Color(215, 248, 248));
        txtrent.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtrent.setForeground(new java.awt.Color(0, 0, 51));
        txtrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrentActionPerformed(evt);
            }
        });
        getContentPane().add(txtrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 210, 30));

        lbl_photo.setBackground(new java.awt.Color(215, 248, 248));
        lbl_photo.setOpaque(true);
        lbl_photo.setPreferredSize(new java.awt.Dimension(134, 172));
        getContentPane().add(lbl_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newnew.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jLabel12MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseWheelMoved

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        // TODO add your handling code here:
            DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
            int selectedIndex = jTable1.getSelectedRow();
        
        
                try {
              int sr = Integer.parseInt(df.getValueAt(selectedIndex,0).toString());
              int resDel = JOptionPane.showConfirmDialog(null, "Do you want to delete ths book","warning",JOptionPane.YES_NO_OPTION);
              
              if(resDel == JOptionPane.YES_OPTION){
                     
                    Class.forName("com.mysql.cj.jdbc.Driver");

                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_rental_system" , "root" , "123456");
                    insert = con.prepareStatement("DELETE FROM admin_book where sr = ?");
                    
                    insert.setInt(1, sr);
                    insert.executeUpdate();
                    
                    
                    
                    JOptionPane.showMessageDialog(this, "Book Deleted Successfully!");
                    table_update();
            
                    txtsr.setText("");
                    txtname.setText("");
                    txtgenres.setText("");
                    txtauthor.setText("");
                    lbl_photo.setText("");  
                    txtrent.setText("");
                    txtsr.requestFocus();
              }
             
           
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(add_books.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         catch (SQLException ex) {
            Logger.getLogger(add_books.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
    }//GEN-LAST:event_btndelActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtauthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtauthorActionPerformed

    private void txtgenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenresActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here
        admin_home obj1 = new admin_home();
        obj1.show(); 
        dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void txtsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsrActionPerformed

    private void btnaddbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddbookMouseClicked
        // TODO add your handling code here:
        add_books ab = new add_books();
        ab.show();
        dispose();
    }//GEN-LAST:event_btnaddbookMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        
        txtsr.setText(df.getValueAt(selectedIndex, 0).toString());
        txtname.setText(df.getValueAt(selectedIndex, 1).toString());
        txtgenres.setText(df.getValueAt(selectedIndex, 2).toString());
        txtauthor.setText(df.getValueAt(selectedIndex, 3).toString());
        txtrent.setText(df.getValueAt(selectedIndex, 4).toString());
        lbl_photo.setText(df.getValueAt(selectedIndex, 5).toString());
       // lbl_photo.setText(df.getValueAt(selectedIndex, 5).toString());
       
        
    
            
    }//GEN-LAST:event_jTable1MouseClicked

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
         try {
              int sr = Integer.parseInt(df.getValueAt(selectedIndex,0).toString());
             
               String name = txtname.getText();
               String genres = txtgenres.getText();
               String author = txtauthor.getText();
               String rent = txtrent.getText();
               
               
               
               
        
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_rental_system" , "root" , "123456");
            insert = con.prepareStatement("UPDATE admin_book set name=? , genres=? , author=? , rent_amt=? where sr = ?");
          
            insert.setString(1, name);
            insert.setString(2, genres);
            insert.setString(3, author);
            insert.setString(4, rent);
            insert.setInt(5, sr);

            
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "BOOK UPDATE");
            table_update();
            
            
                txtsr.setText("");
                txtname.setText("");
                txtgenres.setText("");
                txtauthor.setText("");
                txtrent.setText("");
                lbl_photo.setText(""); 
                txtsr.requestFocus();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(add_books.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         catch (SQLException ex) {
            Logger.getLogger(add_books.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btneditActionPerformed

    private void txtrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddbook;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnedit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_photo;
    private javax.swing.JTextField txtauthor;
    private javax.swing.JLabel txtcover;
    private javax.swing.JTextField txtgenres;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtrent;
    private javax.swing.JTextField txtsr;
    // End of variables declaration//GEN-END:variables

    
}

