/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package book.rental.system;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Shaily Gupta
 */
public class SignUp extends javax.swing.JFrame {
       
    /**
     * Creates new form sign_up
     */
    public SignUp() {
        initComponents();
    }
    
    
    
    //validation
    public boolean validationsignup(){
      String name = txtusername.getText();
      String email = txtemail.getText();
      String phoneno = txtphoneno.getText();
      String pass = txtpass.getText(); 
      String conpass = txtcopass.getText(); 
        if(name.equals("" )){
            JOptionPane.showMessageDialog(this,"Username Required!","Warning",2);
            return false;
        }
        
         if(email.equals("")){
            JOptionPane.showMessageDialog(this,"Please Enter your Email!","Warning",2);
            return false;
        }
         
         if(!email.matches("^.+@.+\\..+$")){
            JOptionPane.showMessageDialog(this,"Please Enter Valid Email!","Warning",2);
            return false;
        }
         
          if(phoneno.equals("")){
            JOptionPane.showMessageDialog(this,"Please Enter Your Phone no.","Warning" ,2);
            return false;
        }
          
          if(phoneno.length()>10){
            JOptionPane.showMessageDialog(this,"Phone no. is too long","Warning" ,2);
            return false;
        }
          
          if(phoneno.length()<10){
            JOptionPane.showMessageDialog(this,"Phone no. is to short","Warning" ,2);
            return false;
        }
          
           if(pass.equals("")){
            JOptionPane.showMessageDialog(this,"Enter password!","Warning",2);
            return false;
        }
           
            if(conpass.equals("")){
            JOptionPane.showMessageDialog(this,"enter confirm password!","Warning",2);
            return false;
        }
             if(!pass.equals(conpass)){
            JOptionPane.showMessageDialog(this,"re_enter password!","Warning",2);
            return false;
        }
        
            return true;
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtphoneno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        txtcopass = new javax.swing.JPasswordField();
        btnsignpu = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        closebtn = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        chkboxreme = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wec.jpg"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wec.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Create New Account");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 300, 50));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("USERNAME");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 90, 20));

        txtusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtusername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusernameKeyTyped(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 240, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("  EMAIL ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 90, 20));

        txtemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 240, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("PHONE NO. ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 90, -1));

        txtphoneno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtphoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphonenoActionPerformed(evt);
            }
        });
        txtphoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphonenoKeyTyped(evt);
            }
        });
        getContentPane().add(txtphoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 240, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("PASSWORD");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("CONFIRM PASSWORD");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 160, 30));

        txtpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 240, 30));

        txtcopass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtcopass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcopassActionPerformed(evt);
            }
        });
        getContentPane().add(txtcopass, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 240, 30));

        btnsignpu.setBackground(new java.awt.Color(0, 102, 102));
        btnsignpu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnsignpu.setForeground(new java.awt.Color(255, 255, 204));
        btnsignpu.setText("SIGN UP");
        btnsignpu.setBorder(null);
        btnsignpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignpuActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 140, 30));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Already have an account?");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 180, 30));

        btnlogin.setBackground(new java.awt.Color(102, 51, 0));
        btnlogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnlogin.setForeground(new java.awt.Color(255, 255, 204));
        btnlogin.setText("Login");
        btnlogin.setBorder(null);
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 80, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("BTB");
        jLabel12.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jLabel12MouseWheelMoved(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book (2).png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        closebtn.setBackground(new java.awt.Color(102, 51, 0));
        closebtn.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        closebtn.setForeground(new java.awt.Color(102, 51, 0));
        closebtn.setText("X");
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        getContentPane().add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 30, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jLabel14.setText("Back");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 70, -1));

        chkboxreme.setBackground(new java.awt.Color(204, 204, 204));
        chkboxreme.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkboxreme.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        chkboxreme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxremeActionPerformed(evt);
            }
        });
        getContentPane().add(chkboxreme, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 20, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wec.jpg"))); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btnsignpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignpuActionPerformed
     // String name,email,phone,password,conpass;
     
        if(validationsignup()==true){
                      
            String query;
        try{    
      String name = txtusername.getText();
      String email = txtemail.getText();
      String phoneno = txtphoneno.getText();
      String pass = txtpass.getText(); 
      String conpass = txtcopass.getText(); 
      
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/book_rental_system" , "root" , "123456");
            Statement st = con.createStatement();
            query = "INSERT INTO userSignup(username,email,phone,password)"+"VALUES('"+name+"' , '"+email+"' , '"+phoneno+"' ,'"+pass+"')";
            st.execute(query);
            
            txtusername.setText("");
            txtemail.setText("");
            txtphoneno.setText("");
            txtpass.setText("");
            txtcopass.setText("");
            
            JOptionPane.showMessageDialog(this, "Your account has been created successfully!!");
   
                user_login obj1 = new user_login();
                obj1.show();
                dispose(); 
          
            
        }catch(Exception e){
            System.out.println("Error!" + e.getMessage());
        }
        }
    }//GEN-LAST:event_btnsignpuActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        user_login obj1 = new user_login();
        obj1.show();
        dispose();
       
    }//GEN-LAST:event_btnloginActionPerformed

    private void jLabel12MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jLabel12MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseWheelMoved

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        // TODO add your handling code here
       welcome obj1 = new welcome();
       obj1.show();
       dispose();
    }//GEN-LAST:event_closebtnMouseClicked

    private void txtcopassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcopassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcopassActionPerformed

    private void txtphonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphonenoActionPerformed

    private void txtusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyTyped
        // TODO add your handling code here:
        char input = evt.getKeyChar();
        if(!(input<'0' || input>'9') && input !='\b'){
            evt.consume();
           JOptionPane.showMessageDialog(this, "Username dosen't contain any numbers","Warning",2);
    }//GEN-LAST:event_txtusernameKeyTyped
    }
    private void txtphonenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphonenoKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
            JOptionPane.showMessageDialog(this, "char are not allowed");
        }
    }//GEN-LAST:event_txtphonenoKeyTyped

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        welcome obj = new welcome();
        obj.show();
        dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void chkboxremeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxremeActionPerformed
        // TODO add your handling code here:
        if(chkboxreme.isSelected()){
            txtpass.setEchoChar((char)0);
            txtcopass.setEchoChar((char)0);
        }
        else{
            txtpass.setEchoChar('*');
            txtcopass.setEchoChar('*');
        }
    }//GEN-LAST:event_chkboxremeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnsignpu;
    private javax.swing.JCheckBox chkboxreme;
    private javax.swing.JLabel closebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField txtcopass;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtphoneno;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
