/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodprojectg;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author kadam
 */
public class camprequest extends javax.swing.JFrame {

    /**
     * Creates new form camprequest
     */
    public camprequest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ftime = new javax.swing.JTextField();
        fcity = new javax.swing.JTextField();
        femail = new javax.swing.JTextField();
        faddress = new javax.swing.JTextField();
        fmobile = new javax.swing.JTextField();
        btnRESET = new javax.swing.JButton();
        btnSUBMIT = new javax.swing.JButton();
        btnCLOSE = new javax.swing.JButton();
        cmbarrangement = new javax.swing.JComboBox<>();
        organiser = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fcamp_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fdate = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(940, 610));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Time schedule:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 120, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Date");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 60, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("City:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Kind of arrangement:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Contact number:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Email ID:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));
        jPanel2.add(ftime, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 200, 25));
        jPanel2.add(fcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 200, 25));
        jPanel2.add(femail, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 200, 25));
        jPanel2.add(faddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 200, 25));
        jPanel2.add(fmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 200, 25));

        btnRESET.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRESET.setText("RESET");
        btnRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRESETActionPerformed(evt);
            }
        });
        jPanel2.add(btnRESET, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 100, 40));

        btnSUBMIT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSUBMIT.setText("SUBMIT");
        btnSUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUBMITActionPerformed(evt);
            }
        });
        jPanel2.add(btnSUBMIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, -1, 40));

        btnCLOSE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCLOSE.setText("CLOSE");
        btnCLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLOSEActionPerformed(evt);
            }
        });
        jPanel2.add(btnCLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 550, 110, 40));

        cmbarrangement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bus", "Venue" }));
        cmbarrangement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbarrangementActionPerformed(evt);
            }
        });
        jPanel2.add(cmbarrangement, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 200, 25));
        jPanel2.add(organiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 200, 25));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Name of organiser:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        fcamp_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcamp_nameActionPerformed(evt);
            }
        });
        jPanel2.add(fcamp_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 200, 25));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Camp Name");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 120, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Address:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, -1));

        fdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdateActionPerformed(evt);
            }
        });
        jPanel2.add(fdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 200, 25));

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ORGANIZE CAMP");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 315, 70));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 90));

        jPanel3.setBackground(new java.awt.Color(153, 0, 51));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 940, 90));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRESETActionPerformed
        // TODO add your handling code here:
 organiser.setText("");
            fdate.setText("");
            ftime.setText("");
            cmbarrangement.setSelectedIndex(0);  // Reset to the first item
            fcity.setText("");
            faddress.setText("");
            fcamp_name.setText("");
              femail.setText("");
            fmobile.setText("");
          
    }//GEN-LAST:event_btnRESETActionPerformed

    private void btnSUBMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUBMITActionPerformed
        // TODO add your handling code here:
        if(organiser.getText().isEmpty()  || ftime.getText().isEmpty() ||fdate.getText().isEmpty() ||fcity.getText().isEmpty() ||
            fcamp_name.getText().isEmpty() ||femail.getText().isEmpty() ||cmbarrangement.getSelectedItem()==null|| fmobile.getText().isEmpty() || faddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all fields.");
            return;
        }
    // to check mobile no.
    if (!fmobile.getText().matches("\\d{10}")) {
        JOptionPane.showMessageDialog(null, "Please enter a valid 10-digit mobile number.");
        return;
    }

    if(evt.getSource() == btnSUBMIT){

        String name = fcamp_name.getText(); 
        String camp_name = organiser.getText();
        String time = ftime.getText();
        String date = fdate.getText();
        String city = fcity.getText();
        String mobile = fmobile.getText();
        String email = femail.getText();
        String arrangement = (String) cmbarrangement.getSelectedItem();
        String address = faddress.getText();
        String Status = "Pending";

        conn c1 = new conn();
        String query = "INSERT INTO camp_info (name,camp_name,city, date,time, address,mobile ,email,arrangement, Status) VALUES (?,?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try {
            PreparedStatement pstmt = c1.c.prepareStatement(query, PreparedStatement.RETURN_GENERATED_KEYS);

            // Set the parameters
            pstmt.setString(1, name);
            pstmt.setString(2, camp_name);
            pstmt.setString(3, city);
            pstmt.setString(4, date);
            pstmt.setString(5, time);
            pstmt.setString(6, address);
            pstmt.setString(7, mobile);
            pstmt.setString(8, email);
            pstmt.setString(9, arrangement);
            pstmt.setString(10, Status);

            // Execute the INSERT statement
            pstmt.executeUpdate();

            // Retrieve the generated request ID
            java.sql.ResultSet generatedKeys = pstmt.getGeneratedKeys();
            if (generatedKeys.next()) {
                int camp_id = generatedKeys.getInt(1);
                JOptionPane.showMessageDialog(null, "Request submitted successfully! Your request ID is: " + camp_id );
                
                organiser.setText("");
            fdate.setText("");
            ftime.setText("");
            cmbarrangement.setSelectedIndex(0);  // Reset to the first item
            fcity.setText("");
            faddress.setText("");
            fcamp_name.setText("");
              femail.setText("");
            fmobile.setText("");
            
            
            } else {
                JOptionPane.showMessageDialog(null, "Error retrieving request ID.");
            }

            // Close the ResultSet
            generatedKeys.close();

        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // You may want to close the connection here (if not handled elsewhere)
        }
    }
    
    
    }//GEN-LAST:event_btnSUBMITActionPerformed

    private void btnCLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLOSEActionPerformed
        // TODO add your handling code here:
   home homeframe = new home();
homeframe.setVisible(true);
homeframe.setLocationRelativeTo(null);
homeframe.pack();
this.setVisible(false); 
    }//GEN-LAST:event_btnCLOSEActionPerformed

    private void fcamp_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcamp_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcamp_nameActionPerformed

    private void fdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fdateActionPerformed

    private void cmbarrangementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbarrangementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbarrangementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(camprequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(camprequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(camprequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(camprequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new camprequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCLOSE;
    private javax.swing.JButton btnRESET;
    private javax.swing.JButton btnSUBMIT;
    private javax.swing.JComboBox<String> cmbarrangement;
    private javax.swing.JTextField faddress;
    private javax.swing.JTextField fcamp_name;
    private javax.swing.JTextField fcity;
    private javax.swing.JTextField fdate;
    private javax.swing.JTextField femail;
    private javax.swing.JTextField fmobile;
    private javax.swing.JTextField ftime;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField organiser;
    // End of variables declaration//GEN-END:variables
}
