package ui;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.ResultSet;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.*;
/**
 *
 * @author dhana
 */
public class CustomerCheckIn extends javax.swing.JFrame {

    /**
     * Creates new form CustomerCheckIn
     */
    public CustomerCheckIn() {
        initComponents();
JTextField cprice = new JTextField();
cprice.setEditable(false);
SimpleDateFormat myFormat = new SimpleDateFormat("yyyy-MM-dd");
    Calendar cal = Calendar.getInstance();
    
    // Set the current date to the 'cindate' field
    cindate.setText(myFormat.format(cal.getTime()));
    cindate.setEditable(false); // Make the date field non-editable
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        cno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cnat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cgender = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cindate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        croom = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbed = new javax.swing.JComboBox<>();
        croomno = new javax.swing.JTextField();
        caddress = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        allot = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 118));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(105, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 150, -1));

        cname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 300, -1));

        cno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(cno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 300, -1));

        jLabel2.setBackground(new java.awt.Color(105, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mobile Number");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 150, -1));

        cnat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(cnat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 300, -1));

        jLabel3.setBackground(new java.awt.Color(105, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nationality");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 150, -1));

        jLabel4.setBackground(new java.awt.Color(105, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 150, -1));

        cemail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cemailActionPerformed(evt);
            }
        });
        getContentPane().add(cemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 300, -1));

        jLabel5.setBackground(new java.awt.Color(105, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 150, -1));

        cgender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        cgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgenderActionPerformed(evt);
            }
        });
        getContentPane().add(cgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 300, -1));

        jLabel6.setBackground(new java.awt.Color(105, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID-Proof");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 150, -1));

        cid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 300, -1));

        jLabel7.setBackground(new java.awt.Color(105, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 150, -1));

        jLabel8.setBackground(new java.awt.Color(105, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Check-In Date");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 150, -1));

        cindate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(cindate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 300, -1));

        jLabel9.setBackground(new java.awt.Color(105, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bed");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 180, 150, -1));

        croom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        croom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deluxe", "Super Deluxe", "VIP" }));
        croom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                croomActionPerformed(evt);
            }
        });
        getContentPane().add(croom, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 300, 300, -1));

        jLabel10.setBackground(new java.awt.Color(105, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Room-Type");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 270, 150, -1));

        jLabel11.setBackground(new java.awt.Color(105, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Room-Number");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 340, 150, -1));

        cbed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        cbed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbedActionPerformed(evt);
            }
        });
        getContentPane().add(cbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 220, 300, -1));

        croomno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(croomno, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 380, 300, -1));

        caddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(caddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 300, -1));

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 0));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1043, 543, -1, -1));

        allot.setBackground(new java.awt.Color(204, 0, 0));
        allot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        allot.setForeground(new java.awt.Color(255, 255, 0));
        allot.setText("Allot Room");
        allot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allotActionPerformed(evt);
            }
        });
        getContentPane().add(allot, new org.netbeans.lib.awtextra.AbsoluteConstraints(1043, 503, -1, -1));

        jButton5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Customer Registration & Check IN.png"))); // NOI18N
        jButton5.setText("Customer Check-In");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 236, 57));

        jButton6.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 204));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/exit.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, 70, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bggg.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cemailActionPerformed

    private void cgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cgenderActionPerformed

    private void croomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_croomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_croomActionPerformed

    private void cbedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbedActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CustomerCheckIn().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new CustomerCheckIn().setVisible(true);
        new CustomerCheckIn().setExtendedState(new CustomerCheckIn().getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Exit?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
        }   
    }//GEN-LAST:event_jButton6ActionPerformed

    private void allotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allotActionPerformed
        // TODO add your handling code here:
String name = cname.getText();
String mob = cno.getText();
String nat = cnat.getText();
String gender = (String) cgender.getSelectedItem();
String email = cemail.getText();
String idProof = cid.getText();
String Address = caddress.getText();
String checkIN = cindate.getText();
String bed = (String) cbed.getSelectedItem();
String roomType = (String) croom.getSelectedItem();
String roomNo = croomno.getText();

// Query to get the room details (price and status) based on room number
String roomQuery = "SELECT price, status, room_type FROM rooms WHERE roomno = ?";
String Query = "SELECT MAX(id) FROM customer";

try {
    ConnectionProvider c = new ConnectionProvider();

    // Fetching the price and status from the rooms table
    PreparedStatement roomStmt = c.c.prepareStatement(roomQuery);
    roomStmt.setString(1, roomNo);
    ResultSet roomRs = roomStmt.executeQuery();

    // Check if the room exists in the rooms table
    String price = "";
    String status = "";
    String type = "";

    // Only proceed if roomRs has results
    if (roomRs.next()) {
        price = roomRs.getString(1); // Assuming price is in the first column (index 0)
        status = roomRs.getString(2);
        type = roomRs.getString(3);// Assuming status is in the second column (index 1)

        // Check if the room is booked
        if ("Booked".equalsIgnoreCase(status)) {
            JOptionPane.showMessageDialog(null, "Room is already booked! Please select another room.");
            return; // Stop execution if the room is booked
        }
    } else {
        JOptionPane.showMessageDialog(null, "Room does not exist! Please check the room number.");
        return; // Stop execution if the room does not exist
    }

    // Proceed only if the price is found
    if (price != null && !price.isEmpty()) {
        ResultSet rs = c.s.executeQuery(Query);
        int id = 1; // Default id in case the table is empty
        if (rs.next()) {
            id = rs.getInt(1) + 1; // Increment the max id
        }

        // Update room status to 'Checked-IN'
        Query = "UPDATE rooms SET status='Checked-IN' WHERE roomno=?";
        PreparedStatement ps1 = c.c.prepareStatement(Query);
        ps1.setString(1, roomNo); // Set room number in the query
        int rowsAffected = ps1.executeUpdate();

        // Insert customer data into the customer table
        Query = "INSERT INTO customer (id, name, mobile, nationality, gender, email, ID_Proof, address, checkin, roomno, bed, roomtype, price, status) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement ps2 = c.c.prepareStatement(Query);
        ps2.setInt(1, id); // Set id
        ps2.setString(2, name);
        ps2.setString(3, mob);
        ps2.setString(4, nat);
        ps2.setString(5, gender);
        ps2.setString(6, email);
        ps2.setString(7, idProof);
        ps2.setString(8, Address);
        ps2.setString(9, checkIN);
        ps2.setString(10, roomNo);
        ps2.setString(11, bed);
        ps2.setString(12, type);
        ps2.setString(13, price); // Use the price retrieved from the rooms table
        ps2.setString(14, "Staying");

        int rowsInserted = ps2.executeUpdate();

        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(null, "Customer details inserted successfully!");
//            setVisible(false);
//            new CustomerCheckIn().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Error inserting customer details.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Room price not found for room number: " + roomNo);
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}

    }//GEN-LAST:event_allotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomerCheckIn frame = new CustomerCheckIn();
                frame.setExtendedState(frame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allot;
    private javax.swing.JTextField caddress;
    private javax.swing.JComboBox<String> cbed;
    private javax.swing.JTextField cemail;
    private javax.swing.JComboBox<String> cgender;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField cindate;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cnat;
    private javax.swing.JTextField cno;
    private javax.swing.JComboBox<String> croom;
    private javax.swing.JTextField croomno;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
