/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Varunkumar lysetti
 */


import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JPasswordField;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;




public class createorg extends javax.swing.JFrame {
Connection conn= user_db_connection.connect();
    PreparedStatement pst=null;
    /**
     * Creates new form createorg
     */
    public createorg() {
        initComponents();
        try {
        conn = user_db_connection.connect();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Failed to connect to the database.");
            System.exit(1); // Exit if the connection is not established
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error connecting to the database: " + e.getMessage());
        e.printStackTrace();
        System.exit(1); // Exit if there was an error
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        orgname = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        orgname1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("Create Organisation");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 400, 50));

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Org. Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 80, 20));

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Mail Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 80, 20));

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("Contact");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 76, -1));

        jLabel7.setBackground(new java.awt.Color(204, 255, 204));
        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 255));
        jLabel7.setText("Org. password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 150, 20));

        orgname.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        getContentPane().add(orgname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 234, -1));

        mail.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 234, -1));

        contact.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 234, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 255));
        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 230, -1));

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 255));
        jLabel6.setText("Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 80, 20));

        orgname1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        orgname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgname1ActionPerformed(evt);
            }
        });
        getContentPane().add(orgname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 234, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picsart_24-09-01_22-01-15-634.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        homepage a=new homepage();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 // Assuming these are your GUI components

// Retrieve input values
String orgName = orgname.getText(); // Get the organization name
String contactInfo = contact.getText(); // Get the contact information
String gmail = mail.getText(); // Get the email
String passwordValue = new String(password.getPassword()); // Get the password
String usernameToCheck = orgname1.getText(); // Get the username to check

try {
    // Check if the username exists in the signup table
    String checkUsernameQuery = "SELECT * FROM signup WHERE username=?";
    PreparedStatement stmtCheck = conn.prepareStatement(checkUsernameQuery);
    stmtCheck.setString(1, usernameToCheck);
    ResultSet rsCheck = stmtCheck.executeQuery();

    // If the username exists
    if (rsCheck.next()) {
        // Now check if the organization name already exists in the orgdata table
        String checkOrgQuery = "SELECT * FROM orgdata WHERE OrgName=?";
        PreparedStatement stmtCheckOrg = conn.prepareStatement(checkOrgQuery);
        stmtCheckOrg.setString(1, orgName);
        ResultSet rsCheckOrg = stmtCheckOrg.executeQuery();

        // If the organization already exists
        if (rsCheckOrg.next()) {
            JOptionPane.showMessageDialog(this, "Organization already exists. Try creating a new one.");
        } else {
            // Proceed with the insert since the org does not exist
            String q = "INSERT INTO orgdata (OrgName, contact, gmail, password, ordadmin) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(q);

            // Set parameters
            pst.setString(1, orgName);
            pst.setString(2, contactInfo);
            pst.setString(3, gmail);
            pst.setString(4, passwordValue);
            pst.setString(5, usernameToCheck); // Store the username in ordadmin column

            // Execute the insert
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Organization created successfully");

            // Redirect to admin home
            homepage adhome = new homepage();
            adhome.setVisible(true);
            this.dispose();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Username does not exist.");
    }
} catch (Exception e) {
    System.out.println("ERROR: " + e.getMessage());
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void orgname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgname1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createorg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createorg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createorg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createorg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createorg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contact;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField orgname;
    private javax.swing.JTextField orgname1;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
